/*
 * Copyright 2010 - 2014 Lars Heuer (heuer[at]semagia.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.semagia.mql.tolog;

import java.io.IOException;
import java.io.Reader;

import com.semagia.mql.MQLException;

/**
 * Entry point to parse tolog.
 *
 * @author Lars Heuer (heuer[at]semagia.com) <a href="http://www.semagia.com/">Semagia</a>
 */
public interface ITologParser {

    /**
     * Parses a tolog query using the provided {@code reader}.
     * 
     * @param reader The reader to utilize.
     * @throws IOException In case of an IO error.
     * @throws MQLException In case of a parsing error.
     */
    public void parse(final Reader reader) throws IOException, MQLException;

    /**
     * Sets the {@link ITologHandler} which receives all events
     * generated by this parser instance.
     * 
     * @param handler A {@link ITologHandler} instance, never {@code null}.
     */
    public void setHandler(ITologHandler handler);

}
